#FROM rabbitmq:3.8-management

#RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp rabbit_mqtt_qos0_queue
# rabbitmq_federation_management???
# build -t slrabbitmq:1.0 .


FROM rabbitmq:3.13.0-beta.2-management

RUN rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp



