services:
  webapi:
    image: identidade-api:1.0
    container_name: identidade-api
    networks:
      - compose-bridge
    ports:
      - "8080:8080"
    #depends_on:
    #  - sqlserver
  sqlserver:
    build: ./Db
    networks:
      - compose-bridge
    ports:
      - 1433:1433      
networks:
  compose-bridge:
    driver: bridge

